
{{- if .Values.exporter.signingKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prometheus-exporter-customerio.fullname" . }}
  labels:
    {{- include "prometheus-exporter-customerio.labels" . | nindent 4 }}
type: Opaque
data:
  signingSecret: |-
    {{ .Values.exporter.signingKey | b64enc }}
{{- end -}}